app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');
Route::get('/benefit', 'WelcomeController@benefit');
Route::get('/screens', 'WelcomeController@screens');
Route::get('/support', 'WelcomeController@support');

Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

//manage schools
Route::group(['middleware' => ['auth','roles'],'roles' => ['super administrator']], function()
{

	Route::get('backup', 'HomeController@backup');
	Route::post('backup', 'HomeController@dumpBackUp');

	Route::resource('schools', 'SchoolsController');
	Route::get(
		'schools/{schools}/users',
		['uses'=>'SchoolsController@getUsers', 'as' => 'schools.users']
	);

	Route::get(
		'schools/{schools}/user/{users}',
		['uses'=>'SchoolsController@getUser', 'as' => 'schools.show-user']
	);

	//create user
	Route::get(
		'schools/{schools}/create-user',
		['uses'=>'SchoolsController@getCreateUser', 'as' => 'schools.create-user']
	);

	Route::post(
		'schools/{schools}/create-user',
		['uses'=>'SchoolsController@postCreateUser', 'as' => 'schools.store-user']
	);

	//edit user
	Route::get(
		'schools/{schools}/edit-user/{users}',
		['uses'=>'SchoolsController@getEditUser', 'as' => 'schools.edit-user']
	);

	Route::patch(
		'schools/{schools}/edit-user/{users}',
		['uses'=>'SchoolsController@patchEditUser', 'as' => 'schools.update-user']
	);

	//edit password
	Route::get(
		'schools/{schools}/edit-password/{users}',
		['uses'=>'SchoolsController@getEditPassword', 'as' => 'schools.edit-password']
	);

	Route::patch(
		'schools/{schools}/edit-password/{users}',
		['uses'=>'SchoolsController@patchEditPassword', 'as' => 'schools.update-password']
	);

	Route::delete(
		'schools/{schools}/user/{users}',
		['uses'=>'SchoolsController@deleteUser', 'as' => 'schools.destory-user']
	);
});

// manage users ----- this has been discarded
Route::group(['middleware' => ['auth','roles'],'roles' => ['administrator', 'school staff']], function()
{	
	Route::resource('users', 'UsersController');
	Route::get(
		'users/{users}/edit-password',
		['uses'=>'UsersController@editPassword', 'as' => 'users.edit-password']
	);

	Route::patch(
		'users/{users}/edit-password',
		['uses'=>'UsersController@updatePassword', 'as' => 'users.update-password']
	);
});

//view information of malaria, view own profile, quiz and attempts
Route::group(['middleware' => ['auth','roles'],'roles' => ['administrator', 'school staff', 'teacher', 'student']], function()
{

	Route::get('information', 'HomeController@information');
	
	Route::controller('user', 'UserController',[
	    'getQuizzes' => 'user.quizzes',
	    'getCountryQuizzes' => 'user.country-quizzes',
	    'getMap' => 'user.map',

	    'getQuizAttempts' => 'user.quiz-attempts',
	    'getQuizAttempt' => 'user.quiz-attempt.show',
	    'postQuizAttempt' => 'user.quiz-attempt.store',
	    'getQuizReview' => 'user.quiz-attempt.review',
	]);
});

//user profile module and ajax request
Route::group(['middleware' => ['auth']], function()
{
	Route::controller('user', 'UserController',[
	    'getIndex' => 'user.index',
	    'getProfile' => 'user.profile',

	    'getProfileEdit' => 'user.profile-edit',
	    'postProfileEdit' => 'user.profile-edit.update',

	    'getProfilePassword' => 'user.profile-password',
	    'postProfilePassword' => 'user.profile-password.update',
	]);

	Route::get(
		'visual/{country}/country-estimate-cases',
		['uses'=>'VisualisationController@getCountryEstimateCases', 'as' => 'visual.estimate-cases']
	);
});


// manage information
Route::group(['middleware' => ['auth','roles'],'roles' => ['school staff']], function()
{
	Route::resource('notes', 'InformationController');
});

//manage classes and quizzes
Route::group(['middleware' => ['auth','roles'],'roles' => ['school staff','teacher']], function()
{
	
	Route::resource('quizzes', 'QuizzesController');
	Route::resource('quizzes.questions', 'QuestionsController');
	Route::delete(
		'quizzes/{quizzes}/questions/{questions}/remove/{choices}',
		['uses'=>'QuestionsController@removeChoice', 'as' => 'quizzes.questions.remove']
	);

	Route::resource('classes', 'ClassesController');
	Route::get(
		'classes/{classes}/students',
		['uses'=>'ClassesController@getStudents', 'as' => 'classes.show-students']
	);

	Route::post(
		'classes/{classes}/students',
		['uses'=>'ClassesController@postStudents', 'as' => 'classes.allocate-students']
	);

	Route::delete(
		'classes/{classes}/students',
		['uses'=>'ClassesController@deleteStudent', 'as' => 'classes.delete-student']
	);

	Route::get(
		'classes/{classes}/class-results',
		['uses'=>'ClassesController@getClassResults', 'as' => 'classes.display-class-results']
	);

	Route::post(
		'classes/{classes}/class-results',
		['uses'=>'ClassesController@postClassResults', 'as' => 'classes.get-class-results']
	);

	Route::get(
		'classes-results',
		['uses'=>'ClassesController@getAllResults', 'as' => 'classes.show-classes-results']
	);

	Route::post(
		'classes-results',
		['uses'=>'ClassesController@postAllResults', 'as' => 'classes.fetch-classes-results']
	);
});


//manage users --roles controller replaced user controller
Route::group(['middleware' => ['auth','roles'],'roles' => ['administrator','school staff','teacher']], function()
{

	Route::controller('roles', 'RolesController',[
	    'getIndex' => 'roles.index',

	    'getStaff' => 'roles.staff',
	    'getTeacher' => 'roles.teacher',
	    'getStudent' => 'roles.student',
	    'getImportStudent' => 'roles.show-import-student',
	    'postImportStudent' => 'roles.create-import-student',

	    'getUser' => 'roles.show-user',
	    'getQuizResults' => 'roles.quiz-results',
	    'getQuizAttempt' => 'roles.quiz-attempt',

	    'getCreateUser' => 'roles.create-user',
	    'postCreateUser' => 'roles.store-user',

	    'getEditUser' => 'roles.edit-user',
	    'patchEditUser' => 'roles.update-user',

	    'getEditPassword' => 'roles.edit-password',
	    'patchEditPassword' => 'roles.update-password',

	    'deleteUser' => 'roles.destory-user',

	]);
});
//Route::get('user/profile',['uses' => 'UserController@showProfile', 'as' => 'user.profile']);

resources/views/app.blade.php
<!doctype html>
<!--[if lt IE 7]><html lang="en" class="no-js ie6"><![endif]-->
<!--[if IE 7]><html lang="en" class="no-js ie7"><![endif]-->
<!--[if IE 8]><html lang="en" class="no-js ie8"><![endif]-->
<!--[if gt IE 8]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->

@include('partials.header')

<body>
   
    <header>
        @include('partials.nav')
    </header>


    <div class="wrapper">
        
        <section>
             <div class="container">
                    
                <div class="section-heading scrollpoint sp-effect3"></div>
                <div class="row">@include('flash::message')</div>
                <div class="row">@yield('content')</div>
            </div>
        </section>

        @include('partials.footer')

    </div>
    @yield('modal')



    {!! Html::script('js/jquery-1.11.1.min.js') !!}
    {!! Html::script('js/bootstrap.min.js') !!}
    {!! Html::script('js/slick.min.js') !!}
    {!! Html::script('js/placeholdem.min.js') !!}
    {!! Html::script('js/rs-plugin/js/jquery.themepunch.plugins.min.js') !!}
    {!! Html::script('js/rs-plugin/js/jquery.themepunch.revolution.min.js') !!}
    {!! Html::script('js/waypoints.min.js') !!}
    {!! Html::script('js/scripts.js') !!}
    {!! Html::script('js/jquery-jvectormap-2.0.2.min.js') !!}
    {!! Html::script('js/jquery-jvectormap-world-mill-en.js') !!}
    {!! Html::script('js/jquery-jvectormap-asia-mill-en.js') !!}
    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0-beta.3/js/select2.min.js"></script>
    <script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
    <script src="{{ asset('/js/bootstrap-switch.js') }}"></script>
    <script src="{{ asset('/js/bootstrap-switch.js') }}"></script>

    <script>
        $(document).ajaxStart(function () {
            $(".loading").show();
        });

        $(document).ajaxComplete(function () {
            $(".loading").hide();
        });
    </script>

    @yield('footer')
</body>

</html>

resources/views/backup.blade.php
@extends('app')

@section('content')
<div class="col-md-8">
	<div class="panel panel-default panel-colorful">
		<div class="panel-heading">
			<h3 class="panel-title">Backup Database</h3>
		</div>

		<div class="panel-body">
			{!! Form::open([ 'url'=>'/backup' ]) !!}
	        <div class="form-group">
				{!! Form::submit("Click to backup",['class'=>'btn btn-primary'])!!}
			</div>
	    	{!! Form::close() !!}
		</div>
	</div>
</div>
@endsection

resources/views/home.blade.php
@extends('app')

@section('content')
<div class="col-md-8">
	<div class="panel panel-default panel-colorful">
		<div class="panel-heading">
			<h3 class="panel-title">Dashboard</h3>
		</div>

		<div class="panel-body">
			@if( Auth::user()->isSuperAdmin() )
				@include('home._super-admin')
			@elseif( Auth::user()->isAdmin() )
				@include('home._admin')
			@elseif( Auth::user()->isSchool() )
				@include('home._staff')
			@elseif( Auth::user()->isTeacher() )
				@include('home._teacher')
			@elseif( Auth::user()->isStudent() )
				@include('home._student')
			@endif
		</div>
	</div>
</div>
<div class="col-md-4">
	<div class="panel panel-default panel-colorful">
		<div class="panel-heading">
			<h3 class="panel-title">Quick Link</h3>
		</div>

		<div class="panel-body">
			<ul style="font-size:18px;">
				@if (Auth::user()->isSuperAdmin())
				<li><a href="{{ route('schools.create') }}">Add a School</a></li>
				@endif
				
				@if (Auth::user()->isAdmin())
				<li><a href="{{ route('roles.create-user','staff') }}">Add a School Staff</a></li>
				@endif

				@if (Auth::user()->isAdmin() || Auth::user()->isSchool())
				<li><a href="{{ route('roles.create-user','teacher') }}">Add a Teacher</a></li>
				@endif

				@if (Auth::user()->isAdmin() || Auth::user()->isSchool() || Auth::user()->isTeacher())
				<li><a href="{{ route('roles.create-user','student') }}">Add a Student</a></li>
				@endif

				@if (Auth::user()->isSchool())
				<li><a href="{{ route('notes.create') }}">Add Country Information</a></li>
				@endif

				@if (Auth::user()->isSchool())
				<li><a href="{{ route('quizzes.create') }}">Add a Quiz</a></li>
				@endif

				@if (Auth::user()->isSchool()||Auth::user()->isTeacher())
				<li><a href="{{ route('classes.show-classes-results') }}">Class Results</a></li>
				@endif

				@if (Auth::user()->isStudent())
					<li><a href="{{ route('user.profile-password') }}">Change Password</a></li>
					@if(!$country->get()->isEmpty())
					<li><a href="{{ route('user.country-quizzes',[$country->iso2]) }}">Country of the Day : {{$country->country_name}}</a></li>
					@endif
				@endif
			</ul>
		</div>	
    </div>
</div>
@endsection

resources/views/notes.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style="width: 800px; margin: 0 auto">
			  <!-- Indicators -->
			  <ol class="carousel-indicators">
			    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="4"></li>
			  </ol>

			  <!-- Wrapper for slides -->
			  <div class="carousel-inner" role="listbox">
			    <div class="item active">
			      <img src="img/malaria/content/1.png" alt="">
			      <div class="carousel-caption">
			        ...
			      </div>
			    </div>
			    <div class="item">
			      <img src="img/malaria/content/2.png" alt="">
			      <div class="carousel-caption">
			        ...
			      </div>
			    </div>
			    <div class="item">
			      <img src="img/malaria/content/3.png" alt="">
			      <div class="carousel-caption">
			        ...
			      </div>
			    </div>
			    <div class="item">
			      <img src="img/malaria/content/4.png" alt="">
			      <div class="carousel-caption">
			        ...
			      </div>
			    </div>
			    <div class="item">
			      <img src="img/malaria/content/5.png" alt="">
			      <div class="carousel-caption">
			        ...
			      </div>
			    </div>
			  </div>

			  <!-- Controls -->
			  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
			    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			    <span class="sr-only">Previous</span>
			  </a>
			  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
			    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			    <span class="sr-only">Next</span>
			  </a>
			</div>
		</div>
	</div>
</div>
@endsection


@section('footer')
<script>
$('.carousel').carousel();
console.log($('.carousel'));
</script>
@endsection