app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');
Route::get('/benefit', 'WelcomeController@benefit');
Route::get('/screens', 'WelcomeController@screens');
Route::get('/support', 'WelcomeController@support');

Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

//manage schools
Route::group(['middleware' => ['auth','roles'],'roles' => ['super administrator']], function()
{

	Route::get('backup', 'HomeController@backup');
	Route::post('backup', 'HomeController@dumpBackUp');

	Route::resource('schools', 'SchoolsController');
	Route::get(
		'schools/{schools}/users',
		['uses'=>'SchoolsController@getUsers', 'as' => 'schools.users']
	);

	Route::get(
		'schools/{schools}/user/{users}',
		['uses'=>'SchoolsController@getUser', 'as' => 'schools.show-user']
	);

	//create user
	Route::get(
		'schools/{schools}/create-user',
		['uses'=>'SchoolsController@getCreateUser', 'as' => 'schools.create-user']
	);

	Route::post(
		'schools/{schools}/create-user',
		['uses'=>'SchoolsController@postCreateUser', 'as' => 'schools.store-user']
	);

	//edit user
	Route::get(
		'schools/{schools}/edit-user/{users}',
		['uses'=>'SchoolsController@getEditUser', 'as' => 'schools.edit-user']
	);

	Route::patch(
		'schools/{schools}/edit-user/{users}',
		['uses'=>'SchoolsController@patchEditUser', 'as' => 'schools.update-user']
	);

	//edit password
	Route::get(
		'schools/{schools}/edit-password/{users}',
		['uses'=>'SchoolsController@getEditPassword', 'as' => 'schools.edit-password']
	);

	Route::patch(
		'schools/{schools}/edit-password/{users}',
		['uses'=>'SchoolsController@patchEditPassword', 'as' => 'schools.update-password']
	);

	Route::delete(
		'schools/{schools}/user/{users}',
		['uses'=>'SchoolsController@deleteUser', 'as' => 'schools.destory-user']
	);
});

// manage users ----- this has been discarded
Route::group(['middleware' => ['auth','roles'],'roles' => ['administrator', 'school staff']], function()
{	
	Route::resource('users', 'UsersController');
	Route::get(
		'users/{users}/edit-password',
		['uses'=>'UsersController@editPassword', 'as' => 'users.edit-password']
	);

	Route::patch(
		'users/{users}/edit-password',
		['uses'=>'UsersController@updatePassword', 'as' => 'users.update-password']
	);
});

//view information of malaria, view own profile, quiz and attempts
Route::group(['middleware' => ['auth','roles'],'roles' => ['administrator', 'school staff', 'teacher', 'student']], function()
{

	Route::get('information', 'HomeController@information');
	
	Route::controller('user', 'UserController',[
	    'getQuizzes' => 'user.quizzes',
	    'getCountryQuizzes' => 'user.country-quizzes',
	    'getMap' => 'user.map',

	    'getQuizAttempts' => 'user.quiz-attempts',
	    'getQuizAttempt' => 'user.quiz-attempt.show',
	    'postQuizAttempt' => 'user.quiz-attempt.store',
	    'getQuizReview' => 'user.quiz-attempt.review',
	]);
});

//user profile module and ajax request
Route::group(['middleware' => ['auth']], function()
{
	Route::controller('user', 'UserController',[
	    'getIndex' => 'user.index',
	    'getProfile' => 'user.profile',

	    'getProfileEdit' => 'user.profile-edit',
	    'postProfileEdit' => 'user.profile-edit.update',

	    'getProfilePassword' => 'user.profile-password',
	    'postProfilePassword' => 'user.profile-password.update',
	]);

	Route::get(
		'visual/{country}/country-estimate-cases',
		['uses'=>'VisualisationController@getCountryEstimateCases', 'as' => 'visual.estimate-cases']
	);
});


// manage information
Route::group(['middleware' => ['auth','roles'],'roles' => ['school staff']], function()
{
	Route::resource('notes', 'InformationController');
});

//manage classes and quizzes
Route::group(['middleware' => ['auth','roles'],'roles' => ['school staff','teacher']], function()
{
	
	Route::resource('quizzes', 'QuizzesController');
	Route::resource('quizzes.questions', 'QuestionsController');
	Route::delete(
		'quizzes/{quizzes}/questions/{questions}/remove/{choices}',
		['uses'=>'QuestionsController@removeChoice', 'as' => 'quizzes.questions.remove']
	);

	Route::resource('classes', 'ClassesController');
	Route::get(
		'classes/{classes}/students',
		['uses'=>'ClassesController@getStudents', 'as' => 'classes.show-students']
	);

	Route::post(
		'classes/{classes}/students',
		['uses'=>'ClassesController@postStudents', 'as' => 'classes.allocate-students']
	);

	Route::delete(
		'classes/{classes}/students',
		['uses'=>'ClassesController@deleteStudent', 'as' => 'classes.delete-student']
	);

	Route::get(
		'classes/{classes}/class-results',
		['uses'=>'ClassesController@getClassResults', 'as' => 'classes.display-class-results']
	);

	Route::post(
		'classes/{classes}/class-results',
		['uses'=>'ClassesController@postClassResults', 'as' => 'classes.get-class-results']
	);

	Route::get(
		'classes-results',
		['uses'=>'ClassesController@getAllResults', 'as' => 'classes.show-classes-results']
	);

	Route::post(
		'classes-results',
		['uses'=>'ClassesController@postAllResults', 'as' => 'classes.fetch-classes-results']
	);
});


//manage users --roles controller replaced user controller
Route::group(['middleware' => ['auth','roles'],'roles' => ['administrator','school staff','teacher']], function()
{

	Route::controller('roles', 'RolesController',[
	    'getIndex' => 'roles.index',

	    'getStaff' => 'roles.staff',
	    'getTeacher' => 'roles.teacher',
	    'getStudent' => 'roles.student',
	    'getImportStudent' => 'roles.show-import-student',
	    'postImportStudent' => 'roles.create-import-student',

	    'getUser' => 'roles.show-user',
	    'getQuizResults' => 'roles.quiz-results',
	    'getQuizAttempt' => 'roles.quiz-attempt',

	    'getCreateUser' => 'roles.create-user',
	    'postCreateUser' => 'roles.store-user',

	    'getEditUser' => 'roles.edit-user',
	    'patchEditUser' => 'roles.update-user',

	    'getEditPassword' => 'roles.edit-password',
	    'patchEditPassword' => 'roles.update-password',

	    'deleteUser' => 'roles.destory-user',

	]);
});
//Route::get('user/profile',['uses' => 'UserController@showProfile', 'as' => 'user.profile']);

app/Http/Controllers/HomeController.php
<?php namespace App\Http\Controllers;

use App\Quiz;
use App\Country;
use App\User;
use App\StudentClass;
use App\Organisation;
use Auth;
use Config;
class HomeController extends Controller {

	/*
	|--------------------------------------------------------------------------
	| Home Controller
	|--------------------------------------------------------------------------
	|
	| This controller renders your application's "dashboard" for users that
	| are authenticated. Of course, you are free to change or remove the
	| controller as you wish. It is just here to get your app started!
	|
	*/

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('auth');
	}

	/**
	 * Show the application dashboard to the user.
	 *
	 * @return Response
	 */
	public function index()
	{
		if(Auth::user()->isSuperAdmin()){
			$schools = Organisation::all();
			return view('home',compact('schools'));
		} elseif(Auth::user()->isAdmin()) {
			return view('home');
		} elseif(Auth::user()->isSchool()) {
			return view('home');
		} elseif(Auth::user()->isTeacher()) {
			return view('home');
		} else {
			$country = Country::countryOfTheDay();
			return view('home',compact('country'));
		}
	}

	/**
	 * Show information slides to learn malaria
	 *
	 * @return Response
	 */
	public function information()
	{
		return view('notes');
	}

	/**
	 * download backups form
	 *
	 * @return Response
	 */
	public function backup()
	{
		return view('backup');
	}

	/**
	 * dump backups
	 *
	 * @return file
	 */
	public function dumpBackUp()
	{
		$host = Config::get('database.connections.mysql.host');
        $database = Config::get('database.connections.mysql.database');
        $username = Config::get('database.connections.mysql.username');
        $password = Config::get('database.connections.mysql.password');
        $backupPath = app_path() . "/../storage/backup/";
        $backupFileName = $database . "-" . date("Y-m-d-H-i-s") . '.sql';
 
        //for linux replace the path with /usr/local/bin/mysqldump (The path might varies).
       	$path = "/usr/bin/mysqldump";
 
        //without password
        //$command = $path . " -u " . $username . " " . $database . " > " . $backupPath . $backupFileName;
        //with password
        $command = $path ." -h " . $host. " -u " . $username . " -p" . $password . " " . $database . " > " . $backupPath . $backupFileName;
        
        system($command);

        header('Content-Description: File Transfer');
		header('Content-Type: application/octet-stream');
		header('Content-Disposition: attachment; filename='.$backupFileName);
		readfile($backupPath.$backupFileName);
		unlink($backupPath.$backupFileName);
    }

}

resources/views/home/_admin.blade.php
<div class="col-md-4">
	<div class="panel panel-info ">
		<div class="panel-heading">
			<div class="row">
				<div class="col-xs-4">
					<i class="fa fa-users fa-4x"></i>
				</div>
				<div class="col-xs-8 text-right">
					<h3>{{Auth::user()->organisation->schools->count()}} staff</h3>
				</div>
			</div>
		</div>
		<a href="{{route('roles.staff')}}">
			<div class="panel-footer">
				<div class="row">
					<div class="col-xs-6">View</div>
					<div class="col-xs-6 text-right">
						<i class="fa fa-arrow-circle-right"></i>
					</div>
				</div>
			</div>
		</a>
	</div>
</div>

<div class="col-md-4">
	<div class="panel panel-info ">
		<div class="panel-heading">
			<div class="row">
				<div class="col-xs-4">
					<i class="fa fa-users fa-4x"></i>
				</div>
				<div class="col-xs-8 text-right">
					<h3>{{Auth::user()->organisation->teachers->count()}} teachers</h3>
				</div>
			</div>
		</div>
		<a href="{{route('roles.teacher')}}">
			<div class="panel-footer">
				<div class="row">
					<div class="col-xs-6">View</div>
					<div class="col-xs-6 text-right">
						<i class="fa fa-arrow-circle-right"></i>
					</div>
				</div>
			</div>
		</a>
	</div>
</div>

<div class="col-md-4">
	<div class="panel panel-info ">
		<div class="panel-heading">
			<div class="row">
				<div class="col-xs-4">
					<i class="fa fa-users fa-4x"></i>
				</div>
				<div class="col-xs-8 text-right">
					<h3>{{Auth::user()->organisation->students->count()}} students</h3>
				</div>
			</div>
		</div>
		<a href="{{route('roles.student')}}">
			<div class="panel-footer">
				<div class="row">
					<div class="col-xs-6">View</div>
					<div class="col-xs-6 text-right">
						<i class="fa fa-arrow-circle-right"></i>
					</div>
				</div>
			</div>
		</a>
	</div>
</div>

resources/views/home/_staff.blade.php
<div class="col-md-4">
	<div class="panel panel-info ">
		<div class="panel-heading">
			<div class="row">
				<div class="col-xs-4">
					<i class="fa fa-users fa-4x"></i>
				</div>
				<div class="col-xs-8 text-right">
					<h3>{{Auth::user()->organisation->teachers->count()}} teachers</h3>
				</div>
			</div>
		</div>
		<a href="{{route('roles.teacher')}}">
			<div class="panel-footer">
				<div class="row">
					<div class="col-xs-6">View</div>
					<div class="col-xs-6 text-right">
						<i class="fa fa-arrow-circle-right"></i>
					</div>
				</div>
			</div>
		</a>
	</div>
</div>

<div class="col-md-4">
	<div class="panel panel-info ">
		<div class="panel-heading">
			<div class="row">
				<div class="col-xs-4">
					<i class="fa fa-users fa-4x"></i>
				</div>
				<div class="col-xs-8 text-right">
					<h3>{{Auth::user()->organisation->students->count()}} students</h3>
				</div>
			</div>
		</div>
		<a href="{{route('roles.student')}}">
			<div class="panel-footer">
				<div class="row">
					<div class="col-xs-6">View</div>
					<div class="col-xs-6 text-right">
						<i class="fa fa-arrow-circle-right"></i>
					</div>
				</div>
			</div>
		</a>
	</div>
</div>

<div class="col-md-4">
	<div class="panel panel-info ">
		<div class="panel-heading">
			<div class="row">
				<div class="col-xs-4">
					<i class="fa fa-certificate fa-4x"></i>
				</div>
				<div class="col-xs-8 text-right">
					<h3>{{Auth::user()->organisation->quizzes->count()}} quizzes</h3>
				</div>
			</div>
		</div>
		<a href="{{route('quizzes.index')}}">
			<div class="panel-footer">
				<div class="row">
					<div class="col-xs-6">View</div>
					<div class="col-xs-6 text-right">
						<i class="fa fa-arrow-circle-right"></i>
					</div>
				</div>
			</div>
		</a>
	</div>
</div>

<div class="col-md-4">
	<div class="panel panel-info ">
		<div class="panel-heading">
			<div class="row">
				<div class="col-xs-4">
					<i class="fa fa-graduation-cap fa-4x"></i>
				</div>
				<div class="col-xs-8 text-right">
					<h3>{{Auth::user()->organisation->classes->count()}} classes</h3>
				</div>
			</div>
		</div>
		<a href="{{route('classes.index')}}">
			<div class="panel-footer">
				<div class="row">
					<div class="col-xs-6">View</div>
					<div class="col-xs-6 text-right">
						<i class="fa fa-arrow-circle-right"></i>
					</div>
				</div>
			</div>
		</a>
	</div>
</div>

resources/views/home/_student.blade.php
<div class="col-md-6">
	<div class="panel panel-info ">
		<div class="panel-heading">
			<div class="row">
				<div class="col-xs-4">
					<i class="fa fa-certificate fa-4x"></i>
				</div>
				<div class="col-xs-8 text-right">
					<h3>{{Auth::user()->organisation->quizzes->count()}} available quizzes</h3>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="col-md-6">
	<div class="panel panel-info ">
		<div class="panel-heading">
			<div class="row">
				<div class="col-xs-4">
					<i class="fa fa-check fa-4x"></i>
				</div>
				<div class="col-xs-8 text-right">
					<h3>{{Auth::user()->quizAttempts->groupBy('quiz_id')->count()}} finished quizzes</h3>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="col-md-6">
	<div class="panel panel-info ">
		<div class="panel-heading">
			<div class="row">
				<div class="col-xs-4">
					<i class="fa fa-thumbs-o-up fa-4x"></i>
				</div>
				<div class="col-xs-8 text-right">
					<h3>{{Auth::user()->quizAttempts->count()}} attempts in total</h3>
				</div>
			</div>
		</div>
	</div>
</div>

resources/views/home/_super-admin.blade.php
<div class="col-md-4">
	<div class="panel panel-info ">
		<div class="panel-heading">
			<div class="row">
				<div class="col-xs-4">
					<i class="fa fa-university fa-4x"></i>
				</div>
				<div class="col-xs-8 text-right">
					<h3>{{$schools->count()}} schools</h3>
				</div>
			</div>
		</div>
		<a href="{{route('schools.index')}}">
			<div class="panel-footer">
				<div class="row">
					<div class="col-xs-6">View</div>
					<div class="col-xs-6 text-right">
						<i class="fa fa-arrow-circle-right"></i>
					</div>
				</div>
			</div>
		</a>
	</div>
</div>

resources/views/home/_teacher.blade.php
<div class="col-md-4">
	<div class="panel panel-info ">
		<div class="panel-heading">
			<div class="row">
				<div class="col-xs-4">
					<i class="fa fa-users fa-4x"></i>
				</div>
				<div class="col-xs-8 text-right">
					<h3>{{Auth::user()->organisation->students->count()}} students</h3>
				</div>
			</div>
		</div>
		<a href="{{route('roles.student')}}">
			<div class="panel-footer">
				<div class="row">
					<div class="col-xs-6">View</div>
					<div class="col-xs-6 text-right">
						<i class="fa fa-arrow-circle-right"></i>
					</div>
				</div>
			</div>
		</a>
	</div>
</div>

<div class="col-md-4">
	<div class="panel panel-info ">
		<div class="panel-heading">
			<div class="row">
				<div class="col-xs-4">
					<i class="fa fa-certificate fa-4x"></i>
				</div>
				<div class="col-xs-8 text-right">
					<h3>{{Auth::user()->organisation->quizzes->count()}} quizzes</h3>
				</div>
			</div>
		</div>
		<a href="{{route('quizzes.index')}}">
			<div class="panel-footer">
				<div class="row">
					<div class="col-xs-6">View</div>
					<div class="col-xs-6 text-right">
						<i class="fa fa-arrow-circle-right"></i>
					</div>
				</div>
			</div>
		</a>
	</div>
</div>

<div class="col-md-4">
	<div class="panel panel-info ">
		<div class="panel-heading">
			<div class="row">
				<div class="col-xs-4">
					<i class="fa fa-graduation-cap fa-4x"></i>
				</div>
				<div class="col-xs-8 text-right">
					<h3>{{Auth::user()->organisation->classes()->whereTeacherId(Auth::id())->count()}} classes</h3>
				</div>
			</div>
		</div>
		<a href="{{route('classes.index')}}">
			<div class="panel-footer">
				<div class="row">
					<div class="col-xs-6">View</div>
					<div class="col-xs-6 text-right">
						<i class="fa fa-arrow-circle-right"></i>
					</div>
				</div>
			</div>
		</a>
	</div>
</div>