app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');
Route::get('/benefit', 'WelcomeController@benefit');
Route::get('/screens', 'WelcomeController@screens');
Route::get('/support', 'WelcomeController@support');

Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

//manage schools
Route::group(['middleware' => ['auth','roles'],'roles' => ['super administrator']], function()
{

	Route::get('backup', 'HomeController@backup');
	Route::post('backup', 'HomeController@dumpBackUp');

	Route::resource('schools', 'SchoolsController');
	Route::get(
		'schools/{schools}/users',
		['uses'=>'SchoolsController@getUsers', 'as' => 'schools.users']
	);

	Route::get(
		'schools/{schools}/user/{users}',
		['uses'=>'SchoolsController@getUser', 'as' => 'schools.show-user']
	);

	//create user
	Route::get(
		'schools/{schools}/create-user',
		['uses'=>'SchoolsController@getCreateUser', 'as' => 'schools.create-user']
	);

	Route::post(
		'schools/{schools}/create-user',
		['uses'=>'SchoolsController@postCreateUser', 'as' => 'schools.store-user']
	);

	//edit user
	Route::get(
		'schools/{schools}/edit-user/{users}',
		['uses'=>'SchoolsController@getEditUser', 'as' => 'schools.edit-user']
	);

	Route::patch(
		'schools/{schools}/edit-user/{users}',
		['uses'=>'SchoolsController@patchEditUser', 'as' => 'schools.update-user']
	);

	//edit password
	Route::get(
		'schools/{schools}/edit-password/{users}',
		['uses'=>'SchoolsController@getEditPassword', 'as' => 'schools.edit-password']
	);

	Route::patch(
		'schools/{schools}/edit-password/{users}',
		['uses'=>'SchoolsController@patchEditPassword', 'as' => 'schools.update-password']
	);

	Route::delete(
		'schools/{schools}/user/{users}',
		['uses'=>'SchoolsController@deleteUser', 'as' => 'schools.destory-user']
	);
});

// manage users ----- this has been discarded
Route::group(['middleware' => ['auth','roles'],'roles' => ['administrator', 'school staff']], function()
{	
	Route::resource('users', 'UsersController');
	Route::get(
		'users/{users}/edit-password',
		['uses'=>'UsersController@editPassword', 'as' => 'users.edit-password']
	);

	Route::patch(
		'users/{users}/edit-password',
		['uses'=>'UsersController@updatePassword', 'as' => 'users.update-password']
	);
});

//view information of malaria, view own profile, quiz and attempts
Route::group(['middleware' => ['auth','roles'],'roles' => ['administrator', 'school staff', 'teacher', 'student']], function()
{

	Route::get('information', 'HomeController@information');
	
	Route::controller('user', 'UserController',[
	    'getQuizzes' => 'user.quizzes',
	    'getCountryQuizzes' => 'user.country-quizzes',
	    'getMap' => 'user.map',

	    'getQuizAttempts' => 'user.quiz-attempts',
	    'getQuizAttempt' => 'user.quiz-attempt.show',
	    'postQuizAttempt' => 'user.quiz-attempt.store',
	    'getQuizReview' => 'user.quiz-attempt.review',
	]);
});

//user profile module and ajax request
Route::group(['middleware' => ['auth']], function()
{
	Route::controller('user', 'UserController',[
	    'getIndex' => 'user.index',
	    'getProfile' => 'user.profile',

	    'getProfileEdit' => 'user.profile-edit',
	    'postProfileEdit' => 'user.profile-edit.update',

	    'getProfilePassword' => 'user.profile-password',
	    'postProfilePassword' => 'user.profile-password.update',
	]);

	Route::get(
		'visual/{country}/country-estimate-cases',
		['uses'=>'VisualisationController@getCountryEstimateCases', 'as' => 'visual.estimate-cases']
	);
});


// manage information
Route::group(['middleware' => ['auth','roles'],'roles' => ['school staff']], function()
{
	Route::resource('notes', 'InformationController');
});

//manage classes and quizzes
Route::group(['middleware' => ['auth','roles'],'roles' => ['school staff','teacher']], function()
{
	
	Route::resource('quizzes', 'QuizzesController');
	Route::resource('quizzes.questions', 'QuestionsController');
	Route::delete(
		'quizzes/{quizzes}/questions/{questions}/remove/{choices}',
		['uses'=>'QuestionsController@removeChoice', 'as' => 'quizzes.questions.remove']
	);

	Route::resource('classes', 'ClassesController');
	Route::get(
		'classes/{classes}/students',
		['uses'=>'ClassesController@getStudents', 'as' => 'classes.show-students']
	);

	Route::post(
		'classes/{classes}/students',
		['uses'=>'ClassesController@postStudents', 'as' => 'classes.allocate-students']
	);

	Route::delete(
		'classes/{classes}/students',
		['uses'=>'ClassesController@deleteStudent', 'as' => 'classes.delete-student']
	);

	Route::get(
		'classes/{classes}/class-results',
		['uses'=>'ClassesController@getClassResults', 'as' => 'classes.display-class-results']
	);

	Route::post(
		'classes/{classes}/class-results',
		['uses'=>'ClassesController@postClassResults', 'as' => 'classes.get-class-results']
	);

	Route::get(
		'classes-results',
		['uses'=>'ClassesController@getAllResults', 'as' => 'classes.show-classes-results']
	);

	Route::post(
		'classes-results',
		['uses'=>'ClassesController@postAllResults', 'as' => 'classes.fetch-classes-results']
	);
});


//manage users --roles controller replaced user controller
Route::group(['middleware' => ['auth','roles'],'roles' => ['administrator','school staff','teacher']], function()
{

	Route::controller('roles', 'RolesController',[
	    'getIndex' => 'roles.index',

	    'getStaff' => 'roles.staff',
	    'getTeacher' => 'roles.teacher',
	    'getStudent' => 'roles.student',
	    'getImportStudent' => 'roles.show-import-student',
	    'postImportStudent' => 'roles.create-import-student',

	    'getUser' => 'roles.show-user',
	    'getQuizResults' => 'roles.quiz-results',
	    'getQuizAttempt' => 'roles.quiz-attempt',

	    'getCreateUser' => 'roles.create-user',
	    'postCreateUser' => 'roles.store-user',

	    'getEditUser' => 'roles.edit-user',
	    'patchEditUser' => 'roles.update-user',

	    'getEditPassword' => 'roles.edit-password',
	    'patchEditPassword' => 'roles.update-password',

	    'deleteUser' => 'roles.destory-user',

	]);
});
//Route::get('user/profile',['uses' => 'UserController@showProfile', 'as' => 'user.profile']);

app/Information.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Quiz Model
 *
 * A table stores either general or country based
 *
 * @author     Kai Yu
 * @since      Delivery Cycle three
 */
class Information extends Model {

	/**
	 * Fillable fields for country or general information
	 *
	 * @var array
	 */
	protected $fillable = [
		'information',
		'organisation_id',
		'country_code'
	];


	/**
	 * allow nullable foriegn key
	 *
	 * @param $value
	 */
	public function setOrganisationIdAttribute($organisation_id)
	{
		$this->attributes['organisation_id'] = $organisation_id ? $organisation_id : null;
	}

	/**
	 * Customize date format, timestamp formate to unix timestamp
	 *
	 */
	protected function getDateFormat()
    {
        return 'U';
    }

	/**
	 * Information can be owned by a country.
	 * 
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function country(){
		return $this->belongsTo('App\Country','country_code','id');
	}

	/**
	 * Organisation can have their own information.
	 * 
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function organisation(){
		return $this->belongsTo('App\Organisation');
	}

}

app/Http/Controllers/InformationController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use App\Information;
use App\Country;
use Auth;
class InformationController extends Controller {
	/**
	 * rules for the class form
	 */
	protected $rules = [
		'information' => 'required|min:3',
		'country_code' => 'required'
	];

	/**
	 * Display a listing of the information.
	 *
	 * @return Response
	 */
	public function index()
	{
		$notes = Auth::user()->organisation->information;
		//dd(Country::findOrFail('AUS')->information);
		return view('information.index',compact('notes'));
	}

	/**
	 * Show the form for creating a new information.
	 *
	 * @return Response
	 */
	public function create()
	{
		$exist_countries = Auth::user()->organisation->information->lists('country_code');
		$countries = Country::whereNotIn('id', $exist_countries)->orderBy('country_name')->lists('country_name','id');
		return view('information.create',compact('countries'));
	}

	/**
	 * Store a newly created information in storage.
	 *
	 * @return Response
	 */
	public function store(Request $request)
	{
		$this->validate($request,$this->rules);

		$request['organisation_id'] = Auth::user()->organisation_id;

		$information = Information::create($request->all());

		flash()->success('Information for country <'.$information->country->country_name.'> has been stored!');
		return redirect('notes');
	}

	/**
	 * Display the specified information.
	 *
	 * @param  Information $information
	 * @return Response
	 */
	public function show(Information $information)
	{
		return view('information.show',compact('information'));
	}

	/**
	 * Show the form for editing the specified information.
	 *
	 * @param  Information  $information
	 * @return Response
	 */
	public function edit(Information $information)
	{
		$exist_countries = Auth::user()->organisation->information->where('country_code','!=',$information->country_code)->lists('country_code');
		$countries = Country::whereNotIn('id', $exist_countries)->orderBy('country_name')->lists('country_name','id');
		return view('information.edit',compact('countries','information'));
	}

	/**
	 * Update the specified information in storage.
	 *
	 * @param  Information $information
	 * @return Response
	 */
	public function update(Information $information,Request $request)
	{
		$this->validate($request,$this->rules);
		flash()->success('Information for country <'.$information->country->country_name.'> has been updated!');
		if($request->input('to_quiz')){
			//$information->update($request->except('to_quiz'));
			$information->update($request->all());
			return redirect()->route('user.country-quizzes',$information->country->iso2);
		}else{
			$information->update($request->all());
			return redirect('notes');
		}
	}

	/**
	 * Remove the specified information from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy(Information $information)
	{
		$information->delete();
		flash()->success('You have successfully deleted a country based note!');
		return redirect('notes');
	}

}

resources/views/information/_form.blade.php
<div class="form-group">
	{!! Form::label('country_code','Country*',['class'=>'col-md-4 control-label'])!!}
	<div class="col-sm-6">
	{!! Form::select('country_code',$countries,null,['id'=>'country_code','class'=>'form-control']) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label('name','Information*',['class'=>'col-md-4 control-label'])!!}
	<div class="col-sm-6">
	{!! Form::textarea('information',null,['class'=>'form-control']) !!}
	</div>
</div>

<div class="form-group">
	<div class="col-sm-offset-4 col-sm-6">
	{!! Form::submit($submitButtonText,['class'=>'btn btn-primary'])!!}
	</div>
</div>

resources/views/information/create.blade.php
@extends('app')

@section('content')

	<div class="col-md-8">
		<div class="panel panel-default panel-colorful">
			<div class="panel-heading">
				<h3 class="panel-title">Create information</h3>
			</div>
			
			<div class="panel-body">
				@include('errors.list')
				{!! Form::model($class = new \App\Information, ['url'=>'/notes','class'=>'form-horizontal']) !!}
					@include('information._form',['submitButtonText'=>'Create Information'])
				{!! Form::close() !!}
			</div>
		</div>
	</div>
@stop

resources/views/information/edit.blade.php
@extends('app')

@section('content')
	<div class="col-md-8">
		<div class="panel panel-default panel-colorful">
			<div class="panel-heading">
				<h3 class="panel-title">Edit Information</h3>
			</div>
			
			<div class="panel-body">
				@include('errors.list')
				{!! Form::model($information,['method'=>'PATCH','route'=>['notes.update',$information],'class'=>'form-horizontal']) !!}
					@include('information._form',['submitButtonText'=>'Update Information'])
				{!! Form::close() !!}
			</div>
		</div>
	</div>
@stop

resources/views/information/index.blade.php
@extends('app')

@section('content')

	
	<div class="panel panel-default panel-colorful">
		<div class="panel-heading">
			<h3 class="panel-title">Information</h3>
			<div class="pull-right">
               <a href="{{route('notes.create')}}" class="btn btn-success">Create information</a>
            </div>
		</div>
		
		<div class="panel-body">
			@if(!$notes->count())
				<div class="alert alert-info">
			        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			        No Information is available.
			    </div>
			@else
            <div class="table-responsive" id="ulist">
			<table class="table">
				<thead>
					<tr>
						<th><span>Information</span></th>
						<th><span>Country</span></th>
						<th><span>Created at</span></th>
						<th>&nbsp;</th>
					</tr>
				</thead>

				<tbody>
				@foreach($notes as $note)
					<tr class="note-info" note-id="{{$note->id}}">
						<td>
							<a href="{{ route('notes.show', [$note->id] ) }}">{!!substr(nl2br($note->information),0,50).'...'!!}</a>
						</td>
						<td>
							{{$note->country->country_name}}
						</td>
						<td>{{$note->created_at->diffForHumans()}}</td>
						<td style="width: 20%;">
							<a href="{{ route( 'notes.edit',[$note] ) }}" class="table-link">
								<span class="fa-stack fa-lg">
									<i class="fa fa-square fa-stack-2x"></i>
									<i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
								</span>
							</a>
							<a href="#" class="table-link text-danger delete-user">
								<span class="fa-stack fa-lg">
									<i class="fa fa-square fa-stack-2x"></i>
									<i class="fa fa-trash-o fa-stack-1x fa-inverse"></i>
								</span>
							</a>
						</td>
					</tr>
				@endforeach
				</tbody>
			</table>
			</div>
			@endif
		</div>
	</div>
@stop

@section('modal')
<div id="deleteModal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Delete Information</h4>
			</div>
			<div class="modal-body">
				<div class="control-group">
					<p>Are you sure you want to delete information <strong id="d-name"></strong>?</p>
					<div></div>
				</div>
			</div>
			<div class="modal-footer">
				{!! Form::open( ['id'=>'delete-form', 'class' => 'form-inline', 'method' => 'DELETE', 'url' => ['classes']]) !!}
				{!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
				<button class="btn btn-default" data-dismiss="modal">Close</button>
				{!! Form::close() !!}
			</div>
		</div>
	</div>
</div>
@stop

@section('footer')
    <script>
    $('.delete-user').on('click',function(e) {
        e.preventDefault();
        $('#d-name').html($(this).closest('.note-info').find('td:nth-child(1)').html());
        infoId = $(this).closest('.note-info').attr('note-id');
        $('#delete-form').attr("action",'/notes/'+infoId)
        $('#deleteModal').modal();
    });
    </script>
@stop

resources/views/information/show.blade.php
@extends('app')

@section('content')
	<div class="col-md-8">
		<div class="panel panel-default panel-colorful">
			<div class="panel-heading">
				<h3 class="panel-title">Information</h3>
			</div>
			
			<div class="panel-body">
				<p><strong>{{$information->country->country_name}}</strong></p>
				<p>{!!nl2br($information->information)!!}</p>
			</div>
		</div>
	</div>
@stop