app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');
Route::get('/benefit', 'WelcomeController@benefit');
Route::get('/screens', 'WelcomeController@screens');
Route::get('/support', 'WelcomeController@support');

Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

//manage schools
Route::group(['middleware' => ['auth','roles'],'roles' => ['super administrator']], function()
{

	Route::get('backup', 'HomeController@backup');
	Route::post('backup', 'HomeController@dumpBackUp');

	Route::resource('schools', 'SchoolsController');
	Route::get(
		'schools/{schools}/users',
		['uses'=>'SchoolsController@getUsers', 'as' => 'schools.users']
	);

	Route::get(
		'schools/{schools}/user/{users}',
		['uses'=>'SchoolsController@getUser', 'as' => 'schools.show-user']
	);

	//create user
	Route::get(
		'schools/{schools}/create-user',
		['uses'=>'SchoolsController@getCreateUser', 'as' => 'schools.create-user']
	);

	Route::post(
		'schools/{schools}/create-user',
		['uses'=>'SchoolsController@postCreateUser', 'as' => 'schools.store-user']
	);

	//edit user
	Route::get(
		'schools/{schools}/edit-user/{users}',
		['uses'=>'SchoolsController@getEditUser', 'as' => 'schools.edit-user']
	);

	Route::patch(
		'schools/{schools}/edit-user/{users}',
		['uses'=>'SchoolsController@patchEditUser', 'as' => 'schools.update-user']
	);

	//edit password
	Route::get(
		'schools/{schools}/edit-password/{users}',
		['uses'=>'SchoolsController@getEditPassword', 'as' => 'schools.edit-password']
	);

	Route::patch(
		'schools/{schools}/edit-password/{users}',
		['uses'=>'SchoolsController@patchEditPassword', 'as' => 'schools.update-password']
	);

	Route::delete(
		'schools/{schools}/user/{users}',
		['uses'=>'SchoolsController@deleteUser', 'as' => 'schools.destory-user']
	);
});

// manage users ----- this has been discarded
Route::group(['middleware' => ['auth','roles'],'roles' => ['administrator', 'school staff']], function()
{	
	Route::resource('users', 'UsersController');
	Route::get(
		'users/{users}/edit-password',
		['uses'=>'UsersController@editPassword', 'as' => 'users.edit-password']
	);

	Route::patch(
		'users/{users}/edit-password',
		['uses'=>'UsersController@updatePassword', 'as' => 'users.update-password']
	);
});

//view information of malaria, view own profile, quiz and attempts
Route::group(['middleware' => ['auth','roles'],'roles' => ['administrator', 'school staff', 'teacher', 'student']], function()
{

	Route::get('information', 'HomeController@information');
	
	Route::controller('user', 'UserController',[
	    'getQuizzes' => 'user.quizzes',
	    'getCountryQuizzes' => 'user.country-quizzes',
	    'getMap' => 'user.map',

	    'getQuizAttempts' => 'user.quiz-attempts',
	    'getQuizAttempt' => 'user.quiz-attempt.show',
	    'postQuizAttempt' => 'user.quiz-attempt.store',
	    'getQuizReview' => 'user.quiz-attempt.review',
	]);
});

//user profile module and ajax request
Route::group(['middleware' => ['auth']], function()
{
	Route::controller('user', 'UserController',[
	    'getIndex' => 'user.index',
	    'getProfile' => 'user.profile',

	    'getProfileEdit' => 'user.profile-edit',
	    'postProfileEdit' => 'user.profile-edit.update',

	    'getProfilePassword' => 'user.profile-password',
	    'postProfilePassword' => 'user.profile-password.update',
	]);

	Route::get(
		'visual/{country}/country-estimate-cases',
		['uses'=>'VisualisationController@getCountryEstimateCases', 'as' => 'visual.estimate-cases']
	);
});


// manage information
Route::group(['middleware' => ['auth','roles'],'roles' => ['school staff']], function()
{
	Route::resource('notes', 'InformationController');
});

//manage classes and quizzes
Route::group(['middleware' => ['auth','roles'],'roles' => ['school staff','teacher']], function()
{
	
	Route::resource('quizzes', 'QuizzesController');
	Route::resource('quizzes.questions', 'QuestionsController');
	Route::delete(
		'quizzes/{quizzes}/questions/{questions}/remove/{choices}',
		['uses'=>'QuestionsController@removeChoice', 'as' => 'quizzes.questions.remove']
	);

	Route::resource('classes', 'ClassesController');
	Route::get(
		'classes/{classes}/students',
		['uses'=>'ClassesController@getStudents', 'as' => 'classes.show-students']
	);

	Route::post(
		'classes/{classes}/students',
		['uses'=>'ClassesController@postStudents', 'as' => 'classes.allocate-students']
	);

	Route::delete(
		'classes/{classes}/students',
		['uses'=>'ClassesController@deleteStudent', 'as' => 'classes.delete-student']
	);

	Route::get(
		'classes/{classes}/class-results',
		['uses'=>'ClassesController@getClassResults', 'as' => 'classes.display-class-results']
	);

	Route::post(
		'classes/{classes}/class-results',
		['uses'=>'ClassesController@postClassResults', 'as' => 'classes.get-class-results']
	);

	Route::get(
		'classes-results',
		['uses'=>'ClassesController@getAllResults', 'as' => 'classes.show-classes-results']
	);

	Route::post(
		'classes-results',
		['uses'=>'ClassesController@postAllResults', 'as' => 'classes.fetch-classes-results']
	);
});


//manage users --roles controller replaced user controller
Route::group(['middleware' => ['auth','roles'],'roles' => ['administrator','school staff','teacher']], function()
{

	Route::controller('roles', 'RolesController',[
	    'getIndex' => 'roles.index',

	    'getStaff' => 'roles.staff',
	    'getTeacher' => 'roles.teacher',
	    'getStudent' => 'roles.student',
	    'getImportStudent' => 'roles.show-import-student',
	    'postImportStudent' => 'roles.create-import-student',

	    'getUser' => 'roles.show-user',
	    'getQuizResults' => 'roles.quiz-results',
	    'getQuizAttempt' => 'roles.quiz-attempt',

	    'getCreateUser' => 'roles.create-user',
	    'postCreateUser' => 'roles.store-user',

	    'getEditUser' => 'roles.edit-user',
	    'patchEditUser' => 'roles.update-user',

	    'getEditPassword' => 'roles.edit-password',
	    'patchEditPassword' => 'roles.update-password',

	    'deleteUser' => 'roles.destory-user',

	]);
});
//Route::get('user/profile',['uses' => 'UserController@showProfile', 'as' => 'user.profile']);

app/Question.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Question Model
 *
 * A table stores quizzes questions
 *
 * @author     Kai Yu
 * @since      Delivery Cycle one
 */
class Question extends Model {

	/**
	 * Fillable fields for a Quiz
	 *
	 * @var array
	 */
	protected $fillable = [
		'quiz_id',
		'question'
	];

	public function scopeRandomOrder($query){
		$query->orderByRaw('RAND()');
	}

	/**
	 * Customize date format, timestamp formate to unix timestamp
	 *
	 */
	protected function getDateFormat()
    {
        return 'U';
    }

	/**
	 * A question is owned by a quiz.
	 * 
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function quiz(){
		return $this->belongsTo('App\Quiz');
	}

	/**
	 * A question can have many choices
	 * 
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function choices(){
		return $this->hasMany('App\Choice');
	}

	/**
	 * A question can have many quiz responses
	 * 
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function quizResponses(){
		return $this->hasMany('App\QuizResponse');
	}
}

app/Http/Controllers/QuestionsController.php
<?php namespace App\Http\Controllers;

use App\Choice;
use App\Question;
use App\Quiz;
use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

/**
 * Questions Controller
 *
 * This controller renders your application's "questions" for users that are authenticated.
 * @author     Kai Yu
 * @since      Delivery Cycle Two
 */
class QuestionsController extends Controller {

	/**
	 * rules for the question form
	 */
	protected $rules = [
		'question' => 'required|min:3|max:255'
	];

	/**
	 * index page, equivalent concept as quizzes.show page, redirect to it
	 *
	 * @return Response
	 */
	public function index(Quiz $quiz)
	{
		return redirect()->route('quizzes.show', [$quiz]);
		//return view('questions.index', compact('quiz'));
	}

	/**
	 * Show the form for creating a new question for a specific quiz.
	 *
	 * @param Quiz $quiz current quiz instance
	 * @return Response
	 */
	public function create(Quiz $quiz)
	{
		return view('questions.create', compact('quiz'));
	}

	/**
	 * Display the specified question within a quiz.
	 *
	 * @param  Quiz $quiz current quiz instance
	 * @param  Question $question current question instance
	 * @return Response
	 */
	public function show(Quiz $quiz, Question $question)
	{
		return view('questions.show',compact('quiz','question'));
	}

	/**
	 * Store a newly created question along with choices in storage.
	 * 
	 * @param Quiz $quiz current quiz instance
	 * @param Request $request current request instance of the HTTP request 
	 * @return Response
	 */
	public function store(Quiz $quiz, Request $request)
	{
		$this->validate($request,$this->rules);

		$inputQuestion = $request->input('question');

		$question = $quiz->questions()->create(['question'=>$inputQuestion]);

		$this->createChoices($request,$question);

		flash()->success('Question has been created!');
		return redirect()->route('quizzes.show', [$quiz]);
	}

	/**
	 * create choices for a question
	 * 
	 * @param Question $Question current quiz question instance
	 * @param Request $request current request instance of the HTTP request
	 */
	private function createChoices(Request $request, Question $question)
	{

		foreach($request->input('choices') as $index=>$choice) {
			$is_answer = ( $index == $request->input('answer') ) ? 1 : 0;
			$choice = $question->choices()->create( [ 'choice_name'=>$choice, 'is_answer'=>$is_answer ] );
		}
	}

	/**
	 * Show the form for editing the specified question.
	 *
	 * @param Question $Question current quiz question instance
	 * @param Quiz $quiz current quiz instance
	 * @return Response
	 */
	public function edit(Quiz $quiz, Question $question)
	{
		return view('questions.edit',compact('quiz','question'));
	}

	/**
	 * Update the specified question in storage.
	 *
	 * @param Question $Question current quiz question instance
	 * @param Quiz $quiz current quiz instance
	 * @param Request $request current request instance of the HTTP request
	 * @return Response
	 */
	public function update(Quiz $quiz , Question $question,Request $request)
	{
		$this->validate($request,$this->rules);

		$inputQuestion = $request->input('question');

		$question->update(['question'=>$inputQuestion]);

		$this->updateChoices($request,$question);

		flash()->success('Question : '.$question->question.' has been updated!');
		return redirect()->route('quizzes.questions.show', [$quiz,$question]);
	}

	/**
	 * Update choices for the question
	 *
	 * @param Request $request current request instance of the HTTP request
	 * @param Question $question current quiz question instance
	 */
	private function updateChoices(Request $request, Question $question) 
	{

		foreach($request->input('choices') as $id=>$choiceTxt) {
			$is_answer = ( $id == $request->input('answer') ) ? 1 : 0;
			if( strpos($id,'new_') !== false ) {
				$question->choices()->create( [ 'choice_name'=>$choiceTxt, 'is_answer'=>$is_answer ] );
			} else {
				$choice = Choice::findOrFail($id);
				$choice->update( [ 'choice_name'=>$choiceTxt, 'is_answer'=>$is_answer ] );
			}
		}
	}

	/**
	 * Remove the specified question from storage.
	 *
	 * @param Question $question current quiz question instance
	 * @param Quiz $quiz current quiz instance
	 * @return Response
	 */
	public function destroy(Quiz $quiz, Question $question)
	{
		$question->delete();
		flash()->success('You have successfully deleted a question!');
		return redirect()->route('quizzes.show', [$quiz]);
	}

	/**
	 * Remove question choice from storage.
	 *
	 * @param Question $question current quiz question instance
	 * @param Quiz $quiz current quiz instance
	 * @param int $choice_id choice id to delete 
	 * @return Response
	 */
	public function removeChoice(Quiz $quiz, Question $question,$choice_id)
	{
		$choice = Choice::findOrFail($choice_id);
		if( !$choice->is_answer ) {
			$choice->delete();
			flash()->success('You have successfully deleted an option!');
		} else {
			flash()->error('Sorry, you cannot delete the choice which is the answer!');
		}
		return redirect()->route('quizzes.questions.edit', [$quiz,$question]);
	}

}

resources/views/questions/_form.blade.php
<div class="form-group">
	{!! Form::label('question','Question:')!!}
	{!! Form::text('question',null,['class'=>'form-control','required'])!!}
</div>

<div class="form-group">
	{!! Form::label('choices','Choices:')!!}
    <ul class="list-group">
        <li class="list-group-item">
			<div class="input-group">
	    		<span class="input-group-addon">
	        		{!! Form::radio('answer',0,['checked'=>'checked'])!!}
	      		</span>
				{!! Form::text('choices[0]',null,['class'=>'form-control','required', 'maxlength' =>255])!!}
			</div>
        </li>
    </ul>

	<a href="#" class="btn btn-sm btn-info btn-add-anwser">Add More Choice</a>
</div>

<div class="form-group">
	{!! Form::submit($submitButtonText,['class'=>'btn btn-primary form-control'])!!}
</div>

resources/views/questions/create.blade.php
@extends('app')

@section('content')
	{!! Breadcrumbs::render('question_create',$quiz) !!}
	<div class="col-md-12 well">
	    <h1>Write a New Question</h1>
	    <hr/>

	    @include('errors.list')
	    {!! Form::open([ 'route'=>['quizzes.questions.index',$quiz->id] ]) !!}
	        @include('questions._form',['submitButtonText'=>'Create Question'])
	    {!! Form::close() !!}
	</div>
@stop

@section('footer')
	<script>
	var choiceCount = 0;
	$('.btn-add-anwser').on('click',function(e) {
		e.preventDefault();
		choiceCount++;
		var template = '<li class="list-group-item choice-container">'+
							'<div class="input-group">'+
		    					'<span class="input-group-addon">'+
		        					'<input type="radio" name="answer" value="'+choiceCount+'">'+
		      					'</span>'+
								'<input type="text" name="choices['+choiceCount+']" class="form-control" required maxlength="255">'+
								'<span class="input-group-btn"><a href="#" class="btn btn-remove">Remove</a></span>' +
							'</div>'+
        				'</li>';

		$(this).prev().append(template);
	});

	$(document).on('click','.btn-remove',function(e) {
		e.preventDefault();

		$(this).closest('.choice-container').remove();
	});
	</script>
@stop

resources/views/questions/edit.blade.php
@extends('app')

@section('content')
    {!! Breadcrumbs::render('question_edit',$quiz,$question) !!}
    <div class="col-md-12 well">
    <h1>Edit Question:{{$question->question}}</h1>

    <hr/>

    @include('errors.list')
    {!! Form::open([ 'route'=>['quizzes.questions.update',$quiz->id,$question->id],'method'=>'PATCH']) !!}
        <div class="form-group">
			{!! Form::label('question','Question:')!!}
			{!! Form::text('question',$question->question,['class'=>'form-control'])!!}
		</div>

		<div class="form-group">
			{!! Form::label('choices','Choices:')!!}
		    <ul class="list-group choice-container">
		    	@foreach($question->choices as $choice)
		        <li class="list-group-item">
					<div class="input-group">
			    		<span class="input-group-addon">
			    			{{--*/ $checked = $choice->is_answer ? 'checked="checked"':'' /*--}}
			        		<input type="radio" name="answer" value="{{$choice->id}}" {{$checked}}>
			      		</span>
						{!! Form::text('choices['.$choice->id.']',$choice->choice_name,['class'=>'form-control','required', 'maxlength' =>255])!!}
						<span class="input-group-btn"><a href="#" class="btn choice-remove" choice-id="{{$choice->id}}">Remove</a></span>
					</div>
		        </li>
		        @endforeach
		    </ul>

			<a href="#" class="btn btn-sm btn-info btn-add-anwser">Add More Choice</a>
		</div>

		<div class="form-group">
			{!! Form::submit('Update Question',['class'=>'btn btn-primary form-control'])!!}
		</div>
    {!! Form::close() !!}
    </div>
@stop

@section('modal')
	<div id="deleteModal" class="modal fade">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title">Delete Choice</h4>
				</div>
				<div class="modal-body">
					<div class="control-group">
						<p>Are you sure you want to delete choice - <strong id="modal-choice"></strong>?</p>
					</div>
				</div>
				<div class="modal-footer">
					{!! Form::open(array('id'=>'delete-form', 'class' => 'form-inline', 'method' => 'DELETE', 'route' => ['quizzes.questions.remove',$quiz->id,$question->id,''])) !!}
                        
                            {!! Form::submit('Delete', array('class' => 'btn btn-danger')) !!}
							<button class="btn btn-default" data-dismiss="modal">Close</button>
                            <input type="hidden" id="choice-id">
                    {!! Form::close() !!}
				</div>
				</form>
			</div>
		</div>
	</div>
@stop

@section('footer')
	<script>
	var choiceCount = 0;
	$('.btn-add-anwser').on('click',function(e) {
		e.preventDefault();
		choiceCount++;
		var template = '<li class="list-group-item choice-container">'+
							'<div class="input-group">'+
		    					'<span class="input-group-addon">'+
		        					'<input type="radio" name="answer" value="new_'+choiceCount+'">'+
		      					'</span>'+
								'<input type="text" name="choices[new_'+choiceCount+']" class="form-control" required maxlength="255">'+
								'<span class="input-group-btn"><a href="#" class="btn btn-remove">Remove</a></span>' +
							'</div>'+
        				'</li>';

		$(this).prev().append(template);
	});

	$('.choice-remove').on('click',function(e) {
		e.preventDefault();
		$('#deleteModal').modal();

		choiceId = $(this).attr('choice-id');
		$('#choice-id').val(choiceId);

		$('#modal-choice').html($(this).closest('.input-group').find('input[type=text]').val());

		currentUrl = $('#delete-form').attr('action');
		$('#delete-form').attr('action', currentUrl+'/'+choiceId);

	});

	$(document).on('click','.btn-remove',function(e) {
		e.preventDefault();

		$(this).closest('.choice-container').remove();
	});
	</script>
@stop

resources/views/questions/index.blade.php
@extends('app')

@section('content')
    {!! Breadcrumbs::render('questions',$quiz) !!}
    <div class="col-md-12 well">
        <h1>
            @if($quiz->country){{$quiz->country->country_name}}@endif Quiz : {{$quiz->title}}
            <div class="btn-group">
                <a href="{{ action('QuizzesController@edit',[$quiz->id]) }}" class="btn btn-primary">Edit Quiz</a>
                <a href="{{ route( 'quizzes.questions.create',[$quiz->id] ) }}" class="btn btn-primary">Add a question</a>
            </div>
        </h1>

        <ul class="list-unstyled">
            <li>Updated {{$quiz->updated_at->diffForHumans() }} </li>
        </ul>

        <hr/>

        @if( !$quiz->questions->count() )
            <div class="alert alert-info">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                This quiz does not have any questions yet.
            </div>
        @else
            @foreach( $quiz->questions as $question )
            <div class="row">
                <div class="col-md-12">
                    <h3>
                        <a href="{{ route( 'quizzes.questions.show',[$quiz->id,$question->id] ) }}">{{$question->question}}</a>
                        <a href="{{ route( 'quizzes.questions.edit',[$quiz->id,$question->id] ) }}" class="btn btn-primary">Edit</a>
                    </h3>
                </div>

                <div class="col-md-12">
                    <ul class="list-group">
                        @foreach( $question->choices as $choice )
                            @if( $choice->is_answer )
                                <li class="list-group-item list-group-item-success">{{$choice->choice_name}}</li>
                            @else
                                <li class="list-group-item">{{$choice->choice_name}}</li>
                            @endif
                        @endforeach
                    </ul>
                </div>
            </div>
    <!--
            <article>
                <h3>
                    <a href="{{route('quizzes.questions.show',[$quiz->id,$question->id])}}">{{$question->question}}</a>
                </h3>
                <div class="body">
                    <ul class="list-group">
                        @foreach( $question->choices as $choice )
                            @if( $choice->is_answer )
                                <li class="list-group-item list-group-item-success">{{$choice->choice_name}}</li>
                            @else
                                <li class="list-group-item">{{$choice->choice_name}}</li>
                            @endif
                        @endforeach
                    </ul>
                </div>
            </article>
    -->
            @endforeach
        @endif
    </div>
@stop

@section('modal')
<div class="question-model modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Add a question</h4>
            </div>
        
            <div class="modal-body">
            </div>
            
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
@stop

resources/views/questions/show.blade.php
@extends('app')

@section('content')
    {!! Breadcrumbs::render('question',$quiz,$question) !!}
    <div class="col-md-12 well">
        <h1>
            Question : {{$question->question}}
            <div class="btn-group">
                <a href="{{ route( 'quizzes.questions.edit',[$quiz->id,$question->id] ) }}" class="btn btn-primary">Edit Question</a>
                <a class="btn btn-danger-malaria btn-danger">Delete this Question</a>
            </div>
        </h1>

        <ul class="list-unstyled">
            <li>Updated {{$question->updated_at->diffForHumans() }} </li>
        </ul>

        <hr/>
        @if( !$question->choices->count() )
            <div class="alert alert-info">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                This question does not have any choices yet.
            </div>
        @else
            <ul class="list-group">
                @foreach( $question->choices as $choice )
                    @if( $choice->is_answer )
                        <li class="list-group-item list-group-item-success">{{$choice->choice_name}}</li>
                    @else
                        <li class="list-group-item">{{$choice->choice_name}}</li>
                    @endif
                @endforeach
            </ul>
        @endif
    </div>
@stop

@section('modal')
    <div id="deleteModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Delete Question</h4>
                </div>
                <div class="modal-body">
                    <div class="control-group">
                        <p>Are you sure you want to delete this question - <strong id="modal-choice">{{$question->question}}</strong>?</p>
                    </div>
                </div>
                <div class="modal-footer">
                    {!! Form::open( ['id'=>'delete-form', 'class' => 'form-inline', 'method' => 'DELETE', 'route' => ['quizzes.questions.destroy',$quiz->id,$question->id]] ) !!}
                        
                            {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                            <button class="btn btn-default" data-dismiss="modal">Close</button>
                    {!! Form::close() !!}
                </div>
                </form>
            </div>
        </div>
    </div>
@stop

@section('footer')
    <script>
    $('.btn-danger-malaria').on('click',function(e) {
        e.preventDefault();
        $('#deleteModal').modal();
    });
    </script>
@stop